(require 'modus-themes)
(setq fore "#5c6a72")
(setq back "#fdf6e3")
(setq modus-operandi-palette-overrides
      '(;; (bg-main "#000000")
        (fg-main "#5c6a72")
        (bg-main "#fdf6e3")
        (fg-mode-line-active bg-main)
        (bg-mode-line-active fg-main)
        (fg-mode-line-inactive f)
        (bg-mode-line-inactive bg-main)
        ))
(load-theme 'modus-operandi :no-confirm)
(set-face-foreground 'vertical-border "#5c6a72")
(set-face-attribute 'mode-line nil :box nil)
(set-face-attribute 'mode-line-inactive nil :box nil)
