(require 'modus-themes)
(setq cyan "#20B2AA")
(setq cyan-bright "#00CCCC")
(setq magenta "#FF1493")
(setq modus-vivendi-palette-overrides
      '(;; (bg-main "#000000")
        (fg-main "#C6C6C4")
        (bg-main "#000000")
        (fg-mode-line-active bg-main)
        (bg-mode-line-active cyan)
        (fg-mode-line-inactive f)
        (bg-mode-line-inactive bg-main)
        ))
(load-theme 'modus-vivendi :no-confirm)
(set-face-foreground 'vertical-border "#000000")
(set-face-attribute 'mode-line nil :box nil)
(set-face-attribute 'mode-line-inactive nil :box nil)
