(require 'modus-themes)
(setq fore "#000000")
(setq back "#f2eede")
(setq modus-operandi-palette-overrides
      '(;; (bg-main "#000000")
        (fg-main "#000000")
        (bg-main "#f2eede")
        (fg-mode-line-active bg-main)
        (bg-mode-line-active fg-main)
        (fg-mode-line-inactive f)
        (bg-mode-line-inactive bg-main)
        ))
(load-theme 'modus-operandi :no-confirm)
(set-face-foreground 'vertical-border "#000000")
(set-face-attribute 'mode-line nil :box nil)
(set-face-attribute 'mode-line-inactive nil :box nil)
